export const FETCH_LOCATIONS_DATA_SUCCESS = "FETCH_LOCATIONS_DATA_SUCCESS";
export const FETCH_LOCATIONS_DATA_FAILURE = "FETCH_LOCATIONS_DATA_FAILURE";
export const SET_ITINERARY_DATA = "SET_ITINERARY_DATA";
export const SET_FINAL_ITINERARY = "SET_FINAL_ITINERARY";
export const SET_DURATION = "SET_DURATION";
