export const FETCH_LOCATIONS_DATA_SUCCESS = "FETCH_LOCATIONS_DATA_SUCCESS";
export const FETCH_LOCATIONS_DATA_FAILURE = "FETCH_LOCATIONS_DATA_FAILURE";
export const SET_ITINERARY_ID = "SET_ITINERARY_ID";